import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/context/auth-context"
import QueryProvider from "@/providers/query-provider"
import { ThemeProvider } from "@/providers/theme-provider"
import "@/styles/globals.css"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"

const poppins = Poppins({
	weight: ["400", "500", "600", "700", "800", "900"],
	style: ["normal", "italic"],
	subsets: ["latin"]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="es" suppressHydrationWarning>
			<body className={`${poppins.className} antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<QueryProvider>
						<AuthProvider>{children}</AuthProvider>
					</QueryProvider>
				</ThemeProvider>
				<Toaster position="top-right" closeButton richColors />
			</body>
		</html>
	)
}
